/**
 * Lead Page Object — encapsulates all interactions with the Lead
 * object in Salesforce Lightning.
 *
 * Pattern notes:
 *  • Each public method represents a user-visible action (navigate,
 *    create, verify).  Tests read like business requirements.
 *  • Private helpers (_fill*, _select*) hide DOM complexity.
 *  • The create method returns a record ID so downstream tests can
 *    chain operations (e.g. convert lead → opportunity).
 */

const { BasePage } = require('./base.page');
const { LEAD } = require('../config/constants');
const { SFHelpers } = require('../utils/sf-helpers');

class LeadPage extends BasePage {

  constructor(page) {
    super(page);
  }

  // ── Navigation ────────────────────────────────────────────────

  async navigateToLeadList() {
    await this.navigateTo(LEAD.TAB_URL_SEGMENT);
  }

  async clickNew() {
    await SFHelpers.clickNewButton(this.page, LEAD.NEW_BTN);
    // Wait for the record form modal / full page to render
    await this.page.waitForTimeout(2000);
  }

  // ── Form Fill ─────────────────────────────────────────────────

  /**
   * Create a lead from a data object.
   * @param {Object} data — generated by fixtures/test-data.js
   * @returns {string|null} the new record ID
   */
  async createLead(data) {
    await this.navigateToLeadList();
    await this.clickNew();

    // Salutation (picklist)
    if (data.salutation) {
      await this._selectPicklist(LEAD.SALUTATION, data.salutation);
    }

    // Text fields
    await this._fillInput(LEAD.FIRST_NAME, data.firstName);
    await this._fillInput(LEAD.LAST_NAME, data.lastName);
    await this._fillInput(LEAD.COMPANY, data.company);

    if (data.title) await this._fillInput(LEAD.TITLE, data.title);
    if (data.email) await this._fillInput(LEAD.EMAIL, data.email);
    if (data.phone) await this._fillInput(LEAD.PHONE, data.phone);

    // Lead Status (picklist — may already be defaulted)
    if (data.leadStatus) {
      try {
        await this._selectPicklist(LEAD.LEAD_STATUS, data.leadStatus);
      } catch {
        // Lead Status often pre-selects a default; non-critical
      }
    }

    // Save
    await SFHelpers.clickSave(this.page, LEAD.SAVE_BTN);

    // Verify success
    await this._verifyCreation(data);

    // Extract record ID from redirect URL
    return this.getRecordIdFromUrl();
  }

  // ── Verification ──────────────────────────────────────────────

  async _verifyCreation(data) {
    // Method 1: Toast message
    try {
      await this.assertToast('was created');
    } catch {
      // Some orgs suppress toasts — fall back to URL check
      await this.page.waitForURL(/\/lightning\/r\/Lead\/\w+\/view/i, {
        timeout: 30_000,
      });
    }
  }

  /**
   * Verify we're on a Lead detail page and key fields are visible.
   */
  async verifyLeadDetail(data) {
    const fullName = `${data.salutation || ''} ${data.firstName} ${data.lastName}`.trim();
    const heading = this.page.getByRole('heading', { name: new RegExp(data.lastName, 'i') });
    await heading.waitFor({ state: 'visible', timeout: 15_000 });
  }

  // ── Private helpers ───────────────────────────────────────────

  async _fillInput(selector, value) {
    await SFHelpers.fillField(this.page, selector, value);
  }

  async _selectPicklist(selector, value) {
    await SFHelpers.selectPicklistValue(this.page, selector, value);
  }
}

module.exports = { LeadPage };
