/**
 * Opportunity Page Object — mirrors LeadPage in structure.
 *
 * Key Salesforce nuance:  Opportunity forms require a Close Date
 * (date picker) and a Stage (picklist).  The date picker in Lightning
 * is notoriously finicky; we bypass the calendar widget by typing
 * directly into the input field.
 */

const { BasePage } = require('./base.page');
const { OPPORTUNITY } = require('../config/constants');
const { SFHelpers } = require('../utils/sf-helpers');

class OpportunityPage extends BasePage {

  constructor(page) {
    super(page);
  }

  // ── Navigation ────────────────────────────────────────────────

  async navigateToOpportunityList() {
    await this.navigateTo(OPPORTUNITY.TAB_URL_SEGMENT);
  }

  async clickNew() {
    await SFHelpers.clickNewButton(this.page, OPPORTUNITY.NEW_BTN);
    await this.page.waitForTimeout(2000);
  }

  // ── Form Fill ─────────────────────────────────────────────────

  /**
   * Create an opportunity from a data object.
   * @param {Object} data — generated by fixtures/test-data.js
   * @returns {string|null} the new record ID
   */
  async createOpportunity(data) {
    await this.navigateToOpportunityList();
    await this.clickNew();

    // Opportunity Name (required)
    await this._fillInput(OPPORTUNITY.OPP_NAME, data.name);

    // Close Date (required) — type directly, avoid date-picker widget
    await this._fillInput(OPPORTUNITY.CLOSE_DATE, data.closeDate);

    // Stage (required picklist)
    await this._selectPicklist(OPPORTUNITY.STAGE, data.stage);

    // Amount (optional)
    if (data.amount) {
      await this._fillInput(OPPORTUNITY.AMOUNT, data.amount);
    }

    // Save
    await SFHelpers.clickSave(this.page, OPPORTUNITY.SAVE_BTN);

    // Verify success
    await this._verifyCreation(data);

    return this.getRecordIdFromUrl();
  }

  // ── Verification ──────────────────────────────────────────────

  async _verifyCreation(data) {
    try {
      await this.assertToast('was created');
    } catch {
      await this.page.waitForURL(/\/lightning\/r\/Opportunity\/\w+\/view/i, {
        timeout: 30_000,
      });
    }
  }

  async verifyOpportunityDetail(data) {
    const heading = this.page.getByRole('heading', {
      name: new RegExp(data.name, 'i'),
    });
    await heading.waitFor({ state: 'visible', timeout: 15_000 });
  }

  // ── Private helpers ───────────────────────────────────────────

  async _fillInput(selector, value) {
    await SFHelpers.fillField(this.page, selector, value);
  }

  async _selectPicklist(selector, value) {
    await SFHelpers.selectPicklistValue(this.page, selector, value);
  }
}

module.exports = { OpportunityPage };
